[package]
name = "chain2paf"
version = "0.1.0"
authors = ["Andrea Guarracino"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.14"
noodles-fasta = "0.46.0"
noodles-core = "0.15.0"
