[package]
name = "chain2paf"
version = "0.1.0"
authors = ["Andrea Guarracino"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.23"
rust-htslib = "0.49.0"
